  version: "3.8"

  services:
    application:
      image: python:latest
      container_name: application
      restart: always
      build: .
      command: python src/main.py
      volumes:
        - .:/app  
      ports: 
        - "3000:3000"
      depends_on:
        - mongo-database

    mongo-database:
      image: mongo
      container_name: mongo-db
      restart: always 
      environment:
        MONGO_INITDB_ROOT_USERNAME: lappis
        MONGO_INITDB_ROOT_PASSWORD: lappis
      ports: 
        - "27017:27017"
      volumes:
        - mongo-data:/data/db

  volumes: 
    mongo-data:
